### PR TITLE
Implement client-side DMA controller

### PR DESCRIPTION
**Pull request by zhemao**
This adds the CPU-side RoCC frontend for the DMA unit. This unit take scare of splitting things into segments and performing virtual address translation, so that the uncore-side DMA engine can focus on contiguous block transfers.

### CODE REVIEW

**Comment by yunsup** [comment]
Is the rocket repository the right place to keep the DMA engine?

**Comment by zhemao** [comment]
This is the piece that sits as a RoCC accelerator on each core. There's another part residing in uncore. Are you suggesting we create a new submodule for all dma stuff?

**Comment by ccelio** [comment]
Is there anything in the DMA's code that depends on rocket?  It seems like it'd be cleaner if it could sit entirely in the uncore (or elsewhere) and just let rocket instantiate it if needed.

**Comment by zhemao** [comment]
Yes, it needs the RoCC interface.

**Comment by ccelio** [comment]
I wonder if we're approaching the point where we need to separate out "Rocket the 5-stage Core" from "Rocket the Library of Processor Components".

**Comment by zhemao** [comment]
That would probably be a good idea, given BOOM and Zscale's dependency on it. Maybe we need a "core" library to complement the "uncore" library.

**Comment by yunsup** [comment]
These are two separate discussions.  I agree with calling the rocket repository the library of processor components.  The DMA stuff really shouldn't be committed to the rocket/uncore repositories.  Would all future RoCC processors be committed to rocket and uncore?  I think the answer is no.

**Comment by zhemao** [comment]
One issue is that this split design requires extra IO ports to be added to the tile. So there's no way of adding this features without modifying rocket in some way. Unless we provide a way of adding extra RoCC/Rocket ports in the configuration file.

**Comment by yunsup** [comment]
You need to think about what should stay in rocket vs. what should be hoisted out as a separate "dma" accelerator.  Changes to the RoCC accelerator stays in Rocket, and everything else specific to the dma unit belongs to a separate "dma" repository.

**Comment by zhemao** [comment]
Sure, that sounds reasonable.

**Comment by zhemao** [comment]
One issue with this is that there is a circular dependency. The DMA frontend depends on rocket for the PTW bundle definitions, while rocket depends on DMA for the client-side DMA bundle definitions. The only way I can see to resolve this is to move the PTW stuff into a different library. Maybe this would be the use case for a "library of processor components" which is separate from rocket.

**Comment by yunsup** [comment]
Doesn’t make sense that rocket depends on DMA frontend IO.

**Comment by zhemao** [comment]
Then how do we provide the port in the TileIO that allows it to connect to the backend unit in uncore?

**Comment by gsmadhusudan** [comment]
Cannot the port definition be an abstract definition used by the core and
un-core ? But located
in the un-core hierarchy ?

On Sat, Dec 19, 2015 at 8:42 AM, Howard Mao <notifications@github.com>
wrote:

> Then how do we provide the port in the TileIO that allows it to connect to
> the backend unit in uncore?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucb-bar/rocket/pull/21#issuecomment-165939874>.
>



-- 
Regards,
Madhu

**Comment by zhemao** [comment]
Well that would require us to have some DMA-related code in uncore, which is what we are trying to avoid by splitting DMA off into a separate submodule. I honestly think it doesn't make much sense to have a separate dma submodule. It seems it would just make things a lot more complicated.

**Comment by zhemao** [comment]
Looks like Henry didn't realize we were still debating this and already merged uncore. We should merge this too so that we don't block further development. If you still disagree with the design, we can debate it and fix it up later.

**Comment by yunsup** [comment]
Let's keep this discussion offline.

**Pull request merged**
