### PR TITLE
Fix a bug in BTB, regarding global history+replays

### PR DESCRIPTION
**Pull request by ccelio**
- global history is updated speculatively in fetch
   - a copy of global history is given to each branch, so mispredicts can
     properly reset history
   - however, pipeline replays do NOT reset history, causing the BHT to unlearn
     the history
   - a "commit" copy of the global history was added to the BTB's bht
   - on a pipeline flush, the commit copy is copied back to the global history

### CODE REVIEW

**Comment by ccelio** [comment]
I would like feedback on a number of things.

- am I using the proper "pipeline flush" signal?
- is the pipeline flush I/O signal the proper way to get from the rocket core to the bht?
- should the commit-copy be made optional, as it will be of marginal use to Rocket?

I verified, at least for dhrystone, that no performance was lost. If this PR looks to be on the correct path, I can spend more time analyzing SPEC performance/differences.

**Comment by zhemao** [comment]
This looks okay to me, but we should wait for Andrew to comment, since I haven't looked at the BTB that much. I'm not certain the pipeline flush signal is hooked up properly.

**Comment by aswaterman** [comment]
So does this actually improve CPI for BOOM?

There's no need to make this feature explicitly optional; setting pipeline_flush to false has that effect.  It might be best to do that for Rocket, actually, until we know this actually improves performance.

The names in the API conflate the mechanism with the behavior; I'd rename pipelineFlushOccurred to something like rollback and rename pipeline_flush to the same thing.  Other than that, it looks OK to me.

**Comment by aswaterman** [comment]
Upon further thought:

Branches all have a copy of the global history, so they can reset the history on misprediction.  Why not do the same thing for pipeline flushes -- i.e., maintain this information in the ROB/commit unit, making this logic external to the BTB?  It seems like better separation of concerns.

**Comment by ccelio** [comment]
> The names in the API conflate the mechanism with the behavior

Thanks, something like "rollback" or "rollbackHistory" is a way better name. 

> Branches all have a copy of the global history, so they can reset the history on misprediction. Why not do the same thing for pipeline flushes -- i.e., maintain this information in the ROB/commit unit, making this logic external to the BTB? It seems like better separation of concerns.

I can explore that idea, but it will require adding another I/O bundle for "rollback.valid" and "rollback.history". I don't think you're suggesting this, but I just want to make it clear that I don't think I can use the existing path that branches use to reset history on mispredicts. 

If you think it's a better separation of concerns, that's fine, I can go ahead and implement your suggested version.


> So does this actually improve CPI for BOOM?

I'll spend some time next week gathering data on this; I first wanted to make sure this looked like the correct path first.

**Comment by ccelio** [comment]
I'm closing this pull request because it's wrong. 

It wrongly assumes that updates to the BTB's BHT occurs during Commit (line 79 in btb.scala), and thus updates the BHT's local copy of the committed global history.  While this is true for Rocket (where both branch redirect and the commit point are both in the Memory stage together), this is not true for other processors which may use the BHT. 

At a minimum, updating the `commit_history` must be broken out from the BHT's `update` function, which is tied to redirecting the fetch unit on a mispredict.

**Pull request closed without merging**
