### PR TITLE
FMALatency Parameter fix

### PR DESCRIPTION
**Pull request by ccelio**
Added Field[Int] to SFMALatency/DFMALatency params.

This barfed in BOOM because operators like subtraction (p(DFMALatency)-1) wouldn't work on "Nothing", so I've made Something out of them.

### CODE REVIEW

**Comment by ccelio** [comment]
Hmmm, not sure why this PR is adding 2 other commits.... so if this is accepted, Andrew, just do your cherry-pick/rebase magic. I still need this branch though, so boom-chip has something to submodule reference against.

**Comment by aswaterman** [comment]
Looks like this PR got screwed up (it has the assert stuff in it), but I manually cherry-picked and pushed the Field[Int] commit.

**Comment by aswaterman** [comment]
... jinx?

**Comment by ccelio** [comment]
Thanks!

**Comment by ccelio** [comment]
For the time being, I need these branches to stay alive until I update to the latest supervisor spec, then I can go back to master.

I promise I'll go through and delete them all once I do.

I should probably stop naming the branches "pr-*" though...

**Pull request closed without merging**
